spring:
  application:
    name: configFinal
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eliasgatica1995/config-properties-proyecto-final.git
server:
  port: 8888